# Generated by Django 4.2.6 on 2023-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_place', '0002_alter_place_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.CharField(choices=[('1.0', '1.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('4.0', '4.0'), ('5.0', '5.0')], max_length=10),
        ),
    ]
