# Generated by Django 4.2.6 on 2023-10-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_post', '0002_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recomended',
            field=models.BooleanField(default=False),
        ),
    ]
